# @package _global_
defaults:
 - _self_

target: adni
task: classification

data_base: 
data_base_cq: /data/local/kgutjahr/datasets/ADNI/dataset_files/age_no_GDTOTAL

num_classes: 3
weights:
live_loading: True
delete_segmentation: False
balanced_accuracy: False
eval_metric: acc
data_orig:
low_data_splits: ['']

# num of features
num_cat: 4
num_con: 5

labels_train: labels_train.pt
labels_val: labels_val.pt 
labelled_identification_train: train_labelled_identification_0.1.pt


data_train_imaging: image_paths_train.pt
data_val_imaging: image_paths_val.pt

data_train_tabular: adni_features_train.csv
data_val_tabular: adni_features_val.csv

field_lengths_tabular: tabular_lengths.pt


data_train_eval_tabular: adni_features_train.csv
labels_train_eval_tabular: labels_train.pt 
data_train_eval_tabular_unlabelled: adni_features_train.csv
labels_train_eval_tabular_unlabelled: labels_train.pt

data_val_eval_tabular: adni_features_val.csv
labels_val_eval_tabular: labels_val.pt 

data_test_eval_tabular: adni_features_test.csv
labels_test_eval_tabular: labels_test.pt 


data_train_eval_imaging: image_paths_train.pt
labels_train_eval_imaging: labels_train.pt
data_train_eval_imaging_unlabelled: image_paths_train.pt
labels_train_eval_imaging_unlabelled: labels_train.pt

data_val_eval_imaging: image_paths_val.pt
labels_val_eval_imaging: labels_val.pt

data_test_eval_imaging: image_paths_test.pt 
labels_test_eval_imaging: labels_test.pt